name: CI - SQL Lint

on:
  push:
  pull_request:

jobs:
  sqlfluff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install sqlfluff sqlfluff-templater-dbt dbt-core

      - name: Run SQLFluff
        run: |
            sqlfluff lint include/dbt/brewery/models \ 
            --dialect databricks \
            --templater jinja